version: "3"
services:
  spring-app:
    container_name: spring-app
    image: "aplbly/fourprac:latest"
    ports:
      - "8080:8080"
  nginx:
    container_name: nginx
    image: "nginx-custom:1"
    ports:
      - "80:80"
    depends_on:
      - spring-app
