OPENVIDU_URL: https://sdrg.myvnc.com
OPENVIDU_SECRET: 1234
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dgrr
    username: root
    password: root
